version: "3.7"
services:
  webserver:
    build:
      args:
        user: root
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: moneytrak
    container_name: moneytrak-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    ports:
        - "5433:5432"
    networks:
      - moneytrak

  postgres:
      image: postgres:9.5-alpine
      container_name: moneytrak-postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=moneytrak_db_user
        - POSTGRES_PASSWORD=moneytrak_db_password
        - POSTGRES_DB=moneytrak_db
      ports:
        - "5434:5432"
      volumes:
        - "./docker-compose/postgres:/var/lib/postgresql/data"
      networks:
        - moneytrak

  nginx:
    image: nginx:alpine
    container_name: moneytrak-nginx
    restart: always
    tty: true
    ports:
      - 8082:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - moneytrak

networks:
  moneytrak:
    driver: bridge
